### ISSUE TITLE
InvalidTypeCast

### ISSUE THREAD

**Issue by jocasousa** [bomrafinha/FormatConverter#105]
Boa tarde Rafa!
Excelente Projeto,

Queria te pedir uma ajuda, eu preciso converter uma resposta de um RESTResponse que veio em JSON para XML e Salvar.
Porem já tentei passar para o seu componente como String da erro, como JsonValue tbm, consegue me ajudar?

` FormatConverter1.JSONtoXML.stringToFile(DM.RESTResPlanos.Content,(ExtractFilePath(Application.ExeName) + '\ENV\Planos3.xml'))`

Abaixo segue os dados que cai no "DM.RESTResPlanos.Content";

`[{"codigo":777,"nome":"PREVSAUDE VIP","comunicado":{"descricao":"Por favor, solicitar ao beneficiário que assine o cupom vinculado","imagem":null},"carteirinha":"http://farmanet.prevsaude.com.br/ows-img/modelos/N777.jpg"},{"codigo":1683,"nome":"TESTE WS -GLM","comunicado":{"descricao":"TESTE","imagem":null},"carteirinha":"http://farmanet.prevsaude.com.br/ows-img/modelos/N1683.jpg"}]`

**Comment by bomrafinha** [comment]
Olá Joca tudo bem? Que bom que o pacote está sendo útil para você :-) Dando uma olhada no JSON que vc está enviando acredito que o erro deva estar acontecendo por iniciar e finalizar o bloco com "[]". É um bug no pacote, como sempre removo os colchetes dos retornos das minhas API não me liguei nisso. Não vou ter como fazer o conserto agora, mas sábado de manhã eu conserto e posto o pacote atualizado. Abraço.

**Comment by jocasousa** [comment]
Agradeço, ate te chamei no whataspp rs, mas ja que vc vai ver pode desconsiderar a mensagem lá!
tem como fazer um teste em cima desse meu Json? ate eu dando um replace nos colchetes ele da access violation.

Abraços

**Comment by jocasousa** [comment]
Bug Resolvido!
